
### 查询所有学生（Day 39）
GET http://localhost:8080/api/students

### 新增学生（Day 40）
POST http://localhost:8080/api/students
Content-Type: application/json

{
  "name": "Run",
  "age": 22,
  "score": 95.5

}

### 修改成绩（Day 41）
PUT http://localhost:8080/api/students/1/score
Content-Type: application/json

{
  "score": 114511
}

### 删除学生（Day 42）
DELETE http://localhost:8080/api/students/12
Content-Type: application/json

